### ISSUE TITLE
Consider pbf or protobuf.js instead of node-protobuf

### ISSUE THREAD

**Issue by kjvalencik** [rastapasta/pokemon-go-mitm-node#13]
Both of these node modules are pretty good, but unlike node-protobuf, are pure JS implementations. That should relax the requirements for install a bit.

Cheers!

**Comment by rastapasta** [comment]
hey hey @kjvalencik ! thanks for your note and motivation to contribute, am fully on your side of a full js implementation!
actually tried a lot to get protobuf.js running, but sadly wise ran into a show-stopping non-syntax3-conform handling of repeated fields - https://github.com/dcodeIO/protobuf.js/issues/432 

if you could get that tackled, both projects would benefit a lot :)

Cheers!

**Comment by kjvalencik** [comment]
Hmm... pbf suffers from the same bug. I'll get a PR up to fix it. However, both libraries have a distinct parse phase that would allow working around this bug. 

I'll see if I can come up with something.

**Comment by Xstasy** [comment]
Can't say I've seen any negative int32/int64's.

**Comment by justinleewells** [comment]
There's a uint in the request envelope. Were you getting hung up on the Illegal wire type error when trying out protobuf.js, @rastapasta?

**Comment by jozsi** [comment]
What if we use the [Google Protobuf JS](https://github.com/google/protobuf/tree/master/js) implementation until a working pure JS one is available? It requires the `protoc` binary, but that's available compiled for all major platforms (OS X, Linux, Windows) and would eliminate the compilation phase (that's a nighmare on Windows - I can share the compiled files if anybody needs them).

**Comment by tvald** [comment]
I put together a drop-in replacement for pokemongo-protobuf which uses Protobuf.js: https://github.com/neon-arcade/pogo-protobufjs

I've also got a branch which provides the replacement configuration:
https://github.com/neon-arcade/pokemon-go-mitm-node/tree/feature/protobufjs

I haven't yet patched protobufjs to fix the errors you encountered, but that's next on my list.

**Comment by tvald** [comment]
I haven't been able to reproduce that particular wire type error, although I've stumbled upon other inconsistencies in the upstream protobuf schemas.  Which particular action / message triggers the problem?

(Unfortunately, I can't easily test many message types due to living in a rather neglected region... -_-)

**Comment by justinleewells** [comment]
I was getting it from the RequestEnvelope message.

**Comment by justinleewells** [comment]
@tvald I branched out my app and used your branch in place of the master and it worked perfectly. It's using protobuf.js instead of node-protobuf?

**Comment by tvald** [comment]
The protobuf.js replacement is on the feature/protobufjs branch in my repo. My master is currently just tracking upstream/master.

**Comment by tvald** [comment]
Here - have a branch of your repo: https://github.com/neon-arcade/pogo-optimizer/tree/feature/protobufjs

There are some errors I'll poke at shortly.

**Comment by justinleewells** [comment]
Sounds good. Tell me how it goes.

**Comment by tvald** [comment]
An upstream schema problem with AssetDigestEntry has been patched (AeonLucid/POGOProtos#71).

There's one slight inconsistency, which is that Protobuf.js fills missing fields with `null`, whereas node-protobuf leaves then `undefined`.

I've fixed the empty-field checks in @justinleewells project, available in [neon-arcade/pogo-optimizer](https://github.com/neon-arcade/pogo-optimizer/tree/feature/protobufjs) on branch `feature/protobufjs`.  I believe that branch should be functional on Windows, unless there are problems with messages that I haven't been able to trigger.

**Comment by Lasertrap00** [comment]
@jozsi Can you share them with me?

**Comment by trisk** [comment]
This has been pretty quiet; I'd be happy to try updating neon-arcade/pogo-protobufjs to current POGOProtos and seeing if anything is still broken. It's unlikely other consumers are affected by the `null` vs `undefined` inconsistency (if they are using `==`, as they should be).
